INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(1001, 'SAHIL SONI', 'LEARN AWS', CURRENT_DATE(),FALSE);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(1002, 'SAHIL SONI', 'LEARN SPRING BOOT', CURRENT_DATE(),FALSE);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(1003, 'SAHIL SONI', 'LEARN KAFKA', CURRENT_DATE(),FALSE);

INSERT INTO TODO(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(1004, 'SAHIL SONI', 'LEARN CLOUD', CURRENT_DATE(),FALSE);